version: '3.4'

services:
  IIC_BACKEND:
    build: .
    image: "${REGISTRY_NAME}devclubiitd/iic_backend:0.1"
    ports:
      - 7500:7500
    healthcheck:
      test: ["CMD", "curl", "http://localhost:7500"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: "unless-stopped" 
    networks:
      - "internal"
      - "reverseproxy"
    environment:
      - VIRTUAL_HOST

networks:
  reverseproxy:
    external:
      name: "reverseproxy"
  internal:
